export const suggestionsData = [
    {label:"A Ladybird Second Picture Book"},
    {label:"A Little Golden Book: Tawny Scrawny Lion"},
    {label:"A Little Golden Book: The Very Best Home for Me"},
    {label:"A Little Golden Book: Walt Disney's Duck Tales, the Secret City Under the Sea"},
    {label:"Adventures of the Six Cousins"},
    {label:"Aesop's Fables for Little Children: The Kite and the Butterfly"},
    {label:"Archie's Double Digest (#190)"},
    {label:"Battleship: The Loss of the Prince of Wales and the Repulse"},
    {label:"Black Beauty"},
    {label:"Dead I Well May Be"},
    {label:"Eragon: Inheritance (Book 1)"},
    {label:"Escape from Genopolis"},
    {label:"Fabel Aesop Untuk Kanak-Kanak: Angin Utara Dengan Matahari"},
    {label:"Fabel Aesop Untuk Kanak-Kanak: Anjing Dengan Bayang-bayangnya"},
    {label:"Fabel Aesop Untuk Kanak-Kanak: Gagak Meniru Helang"},
    {label:"Fabel Aesop Untuk Kanak-Kanak: Mencari Suami Untuk Cik Tikus"},
    {label:"Fabel Aesop Untuk Kanak-Kanak: Rubah dengan Anggur"},
    {label:"Far From the Madding Crowd"},
    {label:"First Aid Manual"},
    {label:"Good Question Good Answer"},
    {label:"Gulliver's Travels"},
    {label:"Hansel and Grettel"},
    {label:"High School Musical: The Junior Novel"},
    {label:"Holy Bible: New Living Translation"},
    {label:"How the Body Works"},
    {label:"Ivanhoe"},
    {label:"Jughead's Double Digest (#137)"},
    {label:"Kidnapped"},
    {label:"King Solomon's Mines"},
    {label:"Little Dorrit"},
    {label:"Lorna Doone"},
    {label:"Nicholas Nickelby"},
    {label:"Oliver Twist"},
    {label:"Overcoming addiction: Positive steps for breaking free of addiction and building self-esteem"},
    {label:"Peacemaker and other stories"},
    {label:"Penguin Modern Classics: Cry: The Beloved Country"},
    {label:"Pocket Sci-Fi: The Final Frontier"},
    {label:"Puss In Boots"},
    {label:"Read it youself: Peter and the Wolf"},
    {label:"Revenge of the Sarong Party Girl"},
    {label:"Round the World in 80 Days"},
    {label:"World's Great Fairy Tales: Tales By Oscar Wilde and Others"},
    {label:"The 10-day MBA"},
    {label:"The Amazing Days of Abby Hayes"},
    {label:"The Chan Handbook"},
    {label:"The Divorce Remedy: The Procen 7-step program for saving your marriage"},
    {label:"The Godfather"},
    {label:"The Hardy Boys: Mystery of Smuggler's Cove"},
    {label:"The Hardy Boys: Mystery of the Whale Tattoo"},
    {label:"The Hardy Boys: The Arctic Patrol Mystery "},
    {label:"The Hardy Boys: The Haunted Fort"},
    {label:"The Hardy Boys: The Mystery of Cabin Island"},
    {label:"The Hardy Boys: While the Clock Ticked"},
    {label:"The King of the Undersea City"},
    {label:"The Little Blue Boy"},
    {label:"The Magic Stone"},
    {label:"The Outcasts of Poker Flat, THe Luck of Roaring Camp and Other Stories"},
    {label:"The Pearl Harbour Papers: Inside the Japanese Plans"},
    {label:"The Pickwick Papers"},
    {label:"The Wow Factor: The 33 things you must (and must not) do to gurantee your edge in today's business world"},
    {label:"Treasure Island"},
    {label:"Treasury of Illustrated Classics: The Time Machine"},
    {label:"Triple Your Reading Speed: The Proven Self-study Plan"},
    {label:"Walt Disney's Mickey Mouse Heads for the Skies"},
    {label:"Well-loved tales: Cinderella"},
    {label:"Well-loved tales: Pinocchio"},
    {label:"Well-Loved Tales: The Sly Fox and the Little Red Hen"},
    {label:"Wings of Fire"},
    {label:"YOU: The Owner's Manual for Teens, a guide to a healthy body annd happy life"},
    {label:"Anak Itik Yang Hodoh"},
    {label:"Disney's 102 Dalmatians: Where's Oddball"},
    {label:"True Singapore Ghost Stories: Book 1"},
    {label:"True Singapore Ghost Stories: Book 2"},
    {label:"True Singapore Ghost Stories: Book 3"},
    {label:"True Singapore Ghost Stories: Book 4"},
    {label:"True Singapore Ghost Stories: Book 5"},
    {label:"True Singapore Ghost Stories: Book 7"},
    {label:"True Singapore Ghost Stories: Book 8"},
    {label:"True Singapore Ghost Stories: Book 11"},
    {label:"True Singapore Ghost Stories: Book 12"},
    {label:"The Flying Trunk"},
    {label:"Noddy Has an Afternoon Off"},
    {label:"Noddy and the Parasol"},
    {label:"Bella Baxter Inn Trouble"},
    {label:"Lat and His Lot Again!"},
    {label:"Zarafa"},
    {label:"Pressure Vessel Handbook: Sixth Edition"},
    {label:"Build the Ultimate Gaming PC"},
    {label:"Great Illlustrated Classics: The Mutiny On Broad HMS Bounty"},
    {label:"The Red Badge of Courage"},
    {label:"The Strange Case of Dr. Jekyll and Mr. Hyde"},
    {label:"The Hardy Boys: The Mark on the Door"},
    {label:"The Hardy Boys: Footprints Under the Window"},
    {label:"The Hardy Boys: The Sinister Signpost"},
    {label:"The Hardy Boys: The Secret Warning"},
    {label:"Warcraft: The Last Guardian"},
    {label:"World of Warcraft: Cycle of Hatred"},
    {label:"Educated: A Memoir"},
    {label:"Washington Black: A novel "},
    {label:"Indianapolis: The True Story of the Worst Sea Disaster in U.S. Naval History and the Fifty-Year Fight to Exonerate an Innocent Man"},
    {label:"Elevation"},
    {label:"The Line Becomes a River: Dispatches from the Border"},
    {label:"The Woman in the Window: A Novel "},
    {label:"Once Upon a River: A Novel"},
    {label:"Children of Blood and Bone (Legacy of Orisha)"},
    {label:"Virgil Wander"},
    {label:"There There: A novel "},
    {label:"The Great Alone: A Novel"},
    {label:"Dopesick: Dealers, Doctors, and the Drug Company that Addicted America"},
    {label:"Wolves of Eden: A Novel "},
    {label:"My Year of Rest and Relaxation"},
    {label:"Frederick Douglass: Prophet of Freedom "},
    {label:"21 Lessons for the 21st Century "},
    {label:"The Witch Elm: A Novel"},
    {label:"Girls Burn Brighter: A Novel"},
    {label:"The Tattooist of Auschwitz: A Novel "},
    {label:"Bad Blood: Secrets and Lies in a Silicon Valley Startup"},
]